# Generated by Django 3.1 on 2022-07-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_mark_student_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='mark',
            new_name='Mark',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='mid',
            new_name='Markid',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='sid',
            new_name='Studid',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='sub_id',
            new_name='Subid',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sid',
            new_name='studid',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_id',
            new_name='Subid',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_name',
            new_name='SubjectName',
        ),
        migrations.AlterModelTable(
            name='mark',
            table='Mark',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subject',
        ),
    ]
