# Generated by Django 3.1 on 2022-07-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20220717_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForeign',
            fields=[
                ('studid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'StudentForeign',
            },
        ),
        migrations.CreateModel(
            name='SubjectForeign',
            fields=[
                ('Subid', models.IntegerField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SubjectForeign',
            },
        ),
        migrations.CreateModel(
            name='MarkForeign',
            fields=[
                ('Markid', models.IntegerField(primary_key=True, serialize=False)),
                ('Mark', models.IntegerField()),
                ('Studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.studentforeign')),
                ('Subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.subjectforeign')),
            ],
            options={
                'db_table': 'MarkForeign',
            },
        ),
    ]
